version: "3.9"

services:
  backend:
    build: ./backend
    container_name: idurar-backend
    ports:
      - "8888:8888"

  frontend:
    build: ./frontend
    container_name: idurar-frontend
    ports:
      - "8067:80"
    depends_on:
      - backend
